//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_List()
        {
            this.Client_Inventory = new HashSet<Client_Inventory>();
            this.User_Login = new HashSet<User_Login>();
            this.Obd_Bulk = new HashSet<Obd_Bulk>();
            this.Obd_Ward_Details = new HashSet<Obd_Ward_Details>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Counsilor_Name { get; set; }
        public string Bangla_Name { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Email { get; set; }
        public Nullable<int> ward { get; set; }
        public Nullable<int> District_Id { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Is_Elected { get; set; }
        public Nullable<bool> Image { get; set; }
        public Nullable<int> Present_Position { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Client_Type_Id { get; set; }
        public Nullable<int> Constituency_Id { get; set; }
        public Nullable<int> Party_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Inventory> Client_Inventory { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Login> User_Login { get; set; }
        public virtual Client_Type Client_Type { get; set; }
        public virtual Constituency Constituency { get; set; }
        public virtual PartyTB PartyTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obd_Bulk> Obd_Bulk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obd_Ward_Details> Obd_Ward_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
