//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Inventory
    {
        public int Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Login_Id { get; set; }
        public Nullable<int> Profile_Id { get; set; }
        public Nullable<int> Free_Sms { get; set; }
        public Nullable<int> Free_Call { get; set; }
        public int Sms_Sent { get; set; }
        public int Call_Sent { get; set; }
        public Nullable<int> Created_By { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public bool Is_Deleted { get; set; }
        public Nullable<int> Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_On { get; set; }
    
        public virtual Client_List Client_List { get; set; }
        public virtual User_Login User_Login { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
