//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTB
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Subject { get; set; }
        public string Job_Title { get; set; }
        public string Company_Name { get; set; }
        public string City { get; set; }
        public string postal_code { get; set; }
        public string Address { get; set; }
        public string Message { get; set; }
        public string IP_Address { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    }
}
