//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Client_List = new HashSet<Client_List>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Division_Id { get; set; }
        public Nullable<bool> Is_Hidden { get; set; }
    
        public virtual ICollection<Client_List> Client_List { get; set; }
    }
}
