//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Spent_Date { get; set; }
        public Nullable<bool> Image { get; set; }
        public string Extension { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> Deleted_By { get; set; }
        public Nullable<System.DateTime> Deleted_On { get; set; }
        public Nullable<int> Account_Head_Id { get; set; }
    
        public virtual Account_Head_TB Account_Head_TB { get; set; }
        public virtual Expense_Type Expense_Type { get; set; }
    }
}
