//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incoming_Calls
    {
        public int Id { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> Called_Time { get; set; }
        public string Server { get; set; }
        public string Call_Unique_Id { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    }
}
