//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CDR_Instant> CDR_Instant { get; set; }
        public virtual DbSet<CDR_Obd> CDR_Obd { get; set; }
        public virtual DbSet<Client_Inventory> Client_Inventory { get; set; }
        public virtual DbSet<Client_List> Client_List { get; set; }
        public virtual DbSet<Client_Type> Client_Type { get; set; }
        public virtual DbSet<Constituency> Constituencies { get; set; }
        public virtual DbSet<ContactTB> ContactTBs { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Expense_Type> Expense_Type { get; set; }
        public virtual DbSet<Incoming_Calls> Incoming_Calls { get; set; }
        public virtual DbSet<Main_Accounts> Main_Accounts { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Obd_Bulk> Obd_Bulk { get; set; }
        public virtual DbSet<Obd_Request> Obd_Request { get; set; }
        public virtual DbSet<Obd_Ward_Details> Obd_Ward_Details { get; set; }
        public virtual DbSet<Offline_Order_Details> Offline_Order_Details { get; set; }
        public virtual DbSet<Online_Order_Details> Online_Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PartyTB> PartyTBs { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Permission_Role> Permission_Role { get; set; }
        public virtual DbSet<Permission_User> Permission_User { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Promotion_Type> Promotion_Type { get; set; }
        public virtual DbSet<Remark> Remarks { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Role_User> Role_User { get; set; }
        public virtual DbSet<Role1> Roles1 { get; set; }
        public virtual DbSet<Sippeer> Sippeers { get; set; }
        public virtual DbSet<Slip_Formats> Slip_Formats { get; set; }
        public virtual DbSet<Sms_Bulk> Sms_Bulk { get; set; }
        public virtual DbSet<Sms_Request> Sms_Request { get; set; }
        public virtual DbSet<Status_> Status_ { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Voter_Slip_Image_Type> Voter_Slip_Image_Type { get; set; }
        public virtual DbSet<Account_Head_TB> Account_Head_TB { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Expense> Expenses { get; set; }
    }
}
