//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Obd_Bulk
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public Nullable<int> Calls_Per_Sec { get; set; }
        public Nullable<int> Retry_Time { get; set; }
        public string Msisdn_File { get; set; }
        public string Play_File { get; set; }
        public Nullable<int> Retry { get; set; }
        public byte[] Created_At { get; set; }
    }
}
