//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obd_Ward_Details
    {
        public int Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Ward { get; set; }
        public Nullable<int> Obd_Bulk_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    
        public virtual Client_List Client_List { get; set; }
        public virtual Obd_Bulk Obd_Bulk { get; set; }
    }
}
