//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obd_Bulk
    {
        public Obd_Bulk()
        {
            this.Obd_Request = new HashSet<Obd_Request>();
            this.Obd_Ward_Details = new HashSet<Obd_Ward_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Obd_Ward_Details_Id { get; set; }
        public Nullable<System.DateTime> Scheduled_Time { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public Nullable<int> Calls_Per_Sec { get; set; }
        public string Play_File { get; set; }
        public Nullable<int> Retry { get; set; }
        public Nullable<int> Total_Calls { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual Client_List Client_List { get; set; }
        public virtual ICollection<Obd_Request> Obd_Request { get; set; }
        public virtual ICollection<Obd_Ward_Details> Obd_Ward_Details { get; set; }
    }
}
