//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obd_Request
    {
        public int Id { get; set; }
        public Nullable<int> Obd_Bulk_Id { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Source_Id { get; set; }
        public Nullable<int> Retry_Count { get; set; }
        public Nullable<System.DateTime> Retry_Schedule { get; set; }
        public string Context { get; set; }
        public string Unique_Id { get; set; }
        public string Last_App { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> Answer_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public string Disposition { get; set; }
        public Nullable<int> Bill_Sec { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Remarks { get; set; }
        public string Server { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    
        public virtual Obd_Bulk Obd_Bulk { get; set; }
    }
}
