//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion_Type
    {
        public Promotion_Type()
        {
            this.Online_Order_Details = new HashSet<Online_Order_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Dispaly_Name { get; set; }
    
        public virtual ICollection<Online_Order_Details> Online_Order_Details { get; set; }
    }
}
