//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Permission_Role = new HashSet<Permission_Role>();
            this.Role_User = new HashSet<Role_User>();
            this.User_Login = new HashSet<User_Login>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Permissions { get; set; }
    
        public virtual ICollection<Permission_Role> Permission_Role { get; set; }
        public virtual ICollection<Role_User> Role_User { get; set; }
        public virtual ICollection<User_Login> User_Login { get; set; }
    }
}
