//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server_log
    {
        public int Id { get; set; }
        public string Remarks_ { get; set; }
        public Nullable<bool> Is_Forwarded { get; set; }
        public string Memory { get; set; }
        public string Processor { get; set; }
        public Nullable<int> Server_Id { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
    
        public virtual ServerTB ServerTB { get; set; }
    }
}
