//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slip_File
    {
        public int Id { get; set; }
        public Nullable<int> Constituency_Id { get; set; }
        public Nullable<int> Ward { get; set; }
        public string File_Name { get; set; }
        public Nullable<int> Voters { get; set; }
        public Nullable<int> Voters_With_Migrate { get; set; }
        public Nullable<int> Files { get; set; }
        public Nullable<bool> Is_Single_File { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual Constituency Constituency { get; set; }
    }
}
