//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slip_Formats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slip_Formats()
        {
            this.Offline_Order_Details = new HashSet<Offline_Order_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Slip_Per_Page { get; set; }
        public Nullable<double> Slip_Height { get; set; }
        public Nullable<double> Slip_Width { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offline_Order_Details> Offline_Order_Details { get; set; }
    }
}
