//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public User_Profile()
        {
            this.User_Login = new HashSet<User_Login>();
            this.Client_Inventory = new HashSet<Client_Inventory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Bangla_Name { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Ward { get; set; }
        public Nullable<int> User_Type { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Image { get; set; }
    
        public virtual ICollection<User_Login> User_Login { get; set; }
        public virtual ICollection<Client_Inventory> Client_Inventory { get; set; }
    }
}
