//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessSuitMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login
    {
        public User_Login()
        {
            this.Permission_User = new HashSet<Permission_User>();
            this.Role_User = new HashSet<Role_User>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> User_Profile_Id { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<bool> Is_Client { get; set; }
    
        public virtual ICollection<Permission_User> Permission_User { get; set; }
        public virtual ICollection<Role_User> Role_User { get; set; }
        public virtual User_Profile User_Profile { get; set; }
        public virtual Role Role { get; set; }
    }
}
